;;; this file is automatically generated, do not edit
#||
Copyright 2015-2021 The Khronos Group Inc.

SPDX-License-Identifier: Apache-2.0 OR MIT
||#

(in-package :vulkan)

(%define-conditions vk-condition
  not-ready
  timeout
  event-set
  event-reset
  incomplete
  suboptimal-khr
  thread-idle-khr
  thread-done-khr
  operation-deferred-khr
  operation-not-deferred-khr
  pipeline-compile-required-ext)

(%define-conditions vk-error
  error-invalid-opaque-capture-address
  error-full-screen-exclusive-mode-lost-ext
  error-not-permitted-ext
  error-fragmentation
  error-invalid-drm-format-modifier-plane-layout-ext
  error-invalid-external-handle
  error-out-of-pool-memory
  error-invalid-shader-nv
  error-validation-failed-ext
  error-incompatible-display-khr
  error-out-of-date-khr
  error-native-window-in-use-khr
  error-surface-lost-khr
  error-unknown
  error-fragmented-pool
  error-format-not-supported
  error-too-many-objects
  error-incompatible-driver
  error-feature-not-present
  error-extension-not-present
  error-layer-not-present
  error-memory-map-failed
  error-device-lost
  error-initialization-failed
  error-out-of-device-memory
  error-out-of-host-memory)

