;;; this file is automatically generated, do not edit
#||
Copyright 2015-2021 The Khronos Group Inc.

SPDX-License-Identifier: Apache-2.0 OR MIT
||#

(in-package :vulkan)

(defconstant +max-physical-device-name-size+ 256
  "Represents VK_MAX_PHYSICAL_DEVICE_NAME_SIZE.") 

(defconstant +uuid-size+ 16
  "Represents VK_UUID_SIZE.") 

(defconstant +luid-size+ 8
  "Represents VK_LUID_SIZE.") 

(defconstant +luid-size-khr+ +luid-size+
  "Represents VK_LUID_SIZE_KHR.") 

(defconstant +max-extension-name-size+ 256
  "Represents VK_MAX_EXTENSION_NAME_SIZE.") 

(defconstant +max-description-size+ 256
  "Represents VK_MAX_DESCRIPTION_SIZE.") 

(defconstant +max-memory-types+ 32
  "Represents VK_MAX_MEMORY_TYPES.") 

(defconstant +max-memory-heaps+ 16
  "Represents VK_MAX_MEMORY_HEAPS.") 

(defconstant +lod-clamp-none+ 1000.0
  "Represents VK_LOD_CLAMP_NONE.") 

(defconstant +remaining-mip-levels+ 4294967295
  "Represents VK_REMAINING_MIP_LEVELS.") 

(defconstant +remaining-array-layers+ 4294967295
  "Represents VK_REMAINING_ARRAY_LAYERS.") 

(defconstant +whole-size+ 18446744073709551615
  "Represents VK_WHOLE_SIZE.") 

(defconstant +attachment-unused+ 4294967295
  "Represents VK_ATTACHMENT_UNUSED.") 

(defconstant +true+ 1
  "Represents VK_TRUE.") 

(defconstant +false+ 0
  "Represents VK_FALSE.") 

(defconstant +queue-family-ignored+ 4294967295
  "Represents VK_QUEUE_FAMILY_IGNORED.") 

(defconstant +queue-family-external+ 4294967294
  "Represents VK_QUEUE_FAMILY_EXTERNAL.") 

(defconstant +queue-family-external-khr+ +queue-family-external+
  "Represents VK_QUEUE_FAMILY_EXTERNAL_KHR.") 

(defconstant +queue-family-foreign-ext+ 4294967293
  "Represents VK_QUEUE_FAMILY_FOREIGN_EXT.") 

(defconstant +subpass-external+ 4294967295
  "Represents VK_SUBPASS_EXTERNAL.") 

(defconstant +max-device-group-size+ 32
  "Represents VK_MAX_DEVICE_GROUP_SIZE.") 

(defconstant +max-device-group-size-khr+ +max-device-group-size+
  "Represents VK_MAX_DEVICE_GROUP_SIZE_KHR.") 

(defconstant +max-driver-name-size+ 256
  "Represents VK_MAX_DRIVER_NAME_SIZE.") 

(defconstant +max-driver-name-size-khr+ +max-driver-name-size+
  "Represents VK_MAX_DRIVER_NAME_SIZE_KHR.") 

(defconstant +max-driver-info-size+ 256
  "Represents VK_MAX_DRIVER_INFO_SIZE.") 

(defconstant +max-driver-info-size-khr+ +max-driver-info-size+
  "Represents VK_MAX_DRIVER_INFO_SIZE_KHR.") 

(defconstant +shader-unused-khr+ 4294967295
  "Represents VK_SHADER_UNUSED_KHR.") 

(defconstant +shader-unused-nv+ +shader-unused-khr+
  "Represents VK_SHADER_UNUSED_NV.") 

(defconstant +max-global-priority-size-ext+ 16
  "Represents VK_MAX_GLOBAL_PRIORITY_SIZE_EXT.") 

