;;; this file is automatically generated, do not edit
#||
Copyright 2015-2021 The Khronos Group Inc.

SPDX-License-Identifier: Apache-2.0 OR MIT
||#

(in-package :vulkan)

(defconstant +max-physical-device-name-size+ 256) 

(defconstant +uuid-size+ 16) 

(defconstant +luid-size+ 8) 

(defconstant +luid-size-khr+ +luid-size+) 

(defconstant +max-extension-name-size+ 256) 

(defconstant +max-description-size+ 256) 

(defconstant +max-memory-types+ 32) 

(defconstant +max-memory-heaps+ 16) 

(defconstant +lod-clamp-none+ 1000.0) 

(defconstant +remaining-mip-levels+ 4294967295) 

(defconstant +remaining-array-layers+ 4294967295) 

(defconstant +whole-size+ 18446744073709551615) 

(defconstant +attachment-unused+ 4294967295) 

(defconstant +true+ 1) 

(defconstant +false+ 0) 

(defconstant +queue-family-ignored+ 4294967295) 

(defconstant +queue-family-external+ 4294967294) 

(defconstant +queue-family-external-khr+ +queue-family-external+) 

(defconstant +queue-family-foreign-ext+ 4294967293) 

(defconstant +subpass-external+ 4294967295) 

(defconstant +max-device-group-size+ 32) 

(defconstant +max-device-group-size-khr+ +max-device-group-size+) 

(defconstant +max-driver-name-size+ 256) 

(defconstant +max-driver-name-size-khr+ +max-driver-name-size+) 

(defconstant +max-driver-info-size+ 256) 

(defconstant +max-driver-info-size-khr+ +max-driver-info-size+) 

(defconstant +shader-unused-khr+ 4294967295) 

(defconstant +shader-unused-nv+ +shader-unused-khr+) 

